apiVersion: apps/v1
kind: Deployment
metadata:
  name: movement-service
  labels:
    app: movement-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movement-service
  template:
    metadata:
      labels:
        app: movement-service
    spec:
      containers:
      - name: movement-service
        image: nunohenriquedeoliveira/ledger-service:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-movement:5432/movementdb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "postgres"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "nuno"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "rabbit"
        - name: SERVER_PORT
          value: "8082"
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "256Mi"

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: movement-service
spec:
  type: NodePort
  selector:
    app: movement-service
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30084
