apiVersion: apps/v1
kind: Deployment
metadata:
  name: commission-service
  labels:
    app: commission-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commission-service
  template:
    metadata:
      labels:
        app: commission-service
    spec:
      containers:
        - name: commission-service
          image: nunohenriquedeoliveira/commission-service:fd26107620aa7678811b8abae16ce9e1a68a8b78
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-commission:5432/commissiondb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: "nuno"
            - name: SPRING_RABBITMQ_PASSWORD
              value: "rabbit"
            - name: SERVER_PORT
              value: "8082"
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: commission-service
  labels:
    app: commission-service
spec:
  type: NodePort
  selector:
    app: commission-service
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      nodePort: 30082
