#### prometheus service
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: 'commission-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8082"]

  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8083"]

  - job_name: 'movement-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["host.docker.internal:8083"]

